/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Captain: { // root type
    id: string; // ID!
    profile: NexusGenRootTypes['Profile']; // Profile!
    rating: number; // Int!
  }
  Profile: { // root type
    address: string; // String!
    email: string; // String!
    gender: string; // String!
    id: string; // ID!
    name: string; // String!
    phone: string; // String!
  }
  Query: {};
  Rating: { // root type
    captain: NexusGenRootTypes['Captain']; // Captain!
    id: string; // ID!
    rating: number; // Int!
    ride: NexusGenRootTypes['Ride']; // Ride!
    user: NexusGenRootTypes['User']; // User!
  }
  Ride: { // root type
    captain: NexusGenRootTypes['Captain']; // Captain!
    dropOffAddress: string; // String!
    fare: number; // Int!
    id: string; // ID!
    rating: NexusGenRootTypes['Rating']; // Rating!
    startAddress: string; // String!
    user: NexusGenRootTypes['User']; // User!
    vehicle: NexusGenRootTypes['Vehicle']; // Vehicle!
  }
  User: { // root type
    id: string; // ID!
    profile: NexusGenRootTypes['Profile']; // Profile!
  }
  Vehicle: { // root type
    captain: NexusGenRootTypes['Captain']; // Captain!
    color: string; // String!
    id: string; // ID!
    make: string; // String!
    model: string; // String!
    plateNumber: number; // Int!
    year: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Captain: { // field return type
    id: string; // ID!
    profile: NexusGenRootTypes['Profile']; // Profile!
    rating: number; // Int!
  }
  Profile: { // field return type
    address: string; // String!
    email: string; // String!
    gender: string; // String!
    id: string; // ID!
    name: string; // String!
    phone: string; // String!
  }
  Query: { // field return type
    ok: boolean; // Boolean!
  }
  Rating: { // field return type
    captain: NexusGenRootTypes['Captain']; // Captain!
    id: string; // ID!
    rating: number; // Int!
    ride: NexusGenRootTypes['Ride']; // Ride!
    user: NexusGenRootTypes['User']; // User!
  }
  Ride: { // field return type
    captain: NexusGenRootTypes['Captain']; // Captain!
    dropOffAddress: string; // String!
    fare: number; // Int!
    id: string; // ID!
    rating: NexusGenRootTypes['Rating']; // Rating!
    startAddress: string; // String!
    user: NexusGenRootTypes['User']; // User!
    vehicle: NexusGenRootTypes['Vehicle']; // Vehicle!
  }
  User: { // field return type
    id: string; // ID!
    profile: NexusGenRootTypes['Profile']; // Profile!
  }
  Vehicle: { // field return type
    captain: NexusGenRootTypes['Captain']; // Captain!
    color: string; // String!
    id: string; // ID!
    make: string; // String!
    model: string; // String!
    plateNumber: number; // Int!
    year: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Captain: { // field return type name
    id: 'ID'
    profile: 'Profile'
    rating: 'Int'
  }
  Profile: { // field return type name
    address: 'String'
    email: 'String'
    gender: 'String'
    id: 'ID'
    name: 'String'
    phone: 'String'
  }
  Query: { // field return type name
    ok: 'Boolean'
  }
  Rating: { // field return type name
    captain: 'Captain'
    id: 'ID'
    rating: 'Int'
    ride: 'Ride'
    user: 'User'
  }
  Ride: { // field return type name
    captain: 'Captain'
    dropOffAddress: 'String'
    fare: 'Int'
    id: 'ID'
    rating: 'Rating'
    startAddress: 'String'
    user: 'User'
    vehicle: 'Vehicle'
  }
  User: { // field return type name
    id: 'ID'
    profile: 'Profile'
  }
  Vehicle: { // field return type name
    captain: 'Captain'
    color: 'String'
    id: 'ID'
    make: 'String'
    model: 'String'
    plateNumber: 'Int'
    year: 'Int'
  }
}

export interface NexusGenArgTypes {
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}